### ISSUE TITLE
Undefined symbols in HLT libraries

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/AliRoot#189]
If AliRoot is build without ZeroMQ, the `AliOptionParser` code is not compiled into `libAliHLTUtil`. Still the header file is included in some components and even used as a base class, e.g. `AliHLTTPCClusterStatComponent`. The corresponding library can not be loaded or linked due to undefined symbol.

@mkrzewic: `AliOptionParser` should be in a separate file and independent of availability of ZeroMQ.

**Comment by mkrzewic** [comment]
@matthiasrichter that has been fixed in the HLT dev branch (https://github.com/ALICEHLT/AliRoot/blob/dev/HLT/BASE/util/AliOptionParser.h), the problem will disappear after merging into master - this is in preparation.

**Comment by matthiasrichter** [comment]
great, thanks. When is this going to happen?

**Comment by mkrzewic** [comment]
I hope soon, the verification is ongoing, see https://alice.its.cern.ch/jira/browse/ATO-398

**Comment by pzhristov** [comment]
Hi @matthiasrichter and @mkrzewic,

Is this issue fixed? If yes, would you close it?

Thanks,
Peter

**Comment by matthiasrichter** [comment]
Hi Peter, looks like the branch mentioned by @mkrzewic is not yet merged to master. So the issue has not yet been fixed.

Cheers
Matthias

**Comment by mkrzewic** [comment]
I cherry-picked the commits that should fix this issue into https://github.com/mkrzewic/AliRoot/tree/AliOptionParser_fix
I can make a pull request, but maybe @matthiasrichter can verify?

**Comment by matthiasrichter** [comment]
@mkrzewic I verified that the fix compiles in my setup and fixes the problem, please go ahead with a PR. I did not check the actual code though.

**Comment by mkrzewic** [comment]
the fix moved to #419
