### ISSUE TITLE
Perform a regression test during PR tests

### ISSUE THREAD

**Issue by sawenzel** [alisw/AliRoot#274]
This is a feature request to run a simple regression test, that performs a complete processing from simulation to reconstrution, during the PR checks.

This would let us identify many problems early.  

The test vmctest/gun with 1 event seems appropriate since it tests Geant4 + Geant3 + reconstruction.

The steps to be done are:

- [x]  Make vmctest/gun/runtest.sh perform correctly

- [x]  Make a recipe for alibuild to perform the test

- [x]  Hook the test to the build system

**Comment by sawenzel** [comment]
Taking care of step 1 and 2....

**Comment by dberzano** [comment]
Hi @sawenzel, this is related to alisw/alidist#778, right?

**Comment by sawenzel** [comment]
@dberzano : right

**Comment by sawenzel** [comment]
Is in place. Closing.
