### ISSUE TITLE
AliAODPWG4Particle hides overloaded virtual

### ISSUE THREAD

**Issue by aaniin** [alisw/AliRoot#368]
Hello @gconesab ,

I wonder whether you see a good fix for this hiding of an inherited function. 
```c++
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/osx_x86-64/AliRoot/0-1/include/AliAODPWG4Particle.h:44:20: warning: 'AliAODPWG4Particle::Momentum' hides overloaded virtual function [-Woverloaded-virtual]
DEBUG:AliPhysics:0:   TLorentzVector * Momentum() const                  { return fMomentum ; }
DEBUG:AliPhysics:0:                    ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/osx_x86-64/AliRoot/0-1/include/AliVParticle.h:47:20: note: hidden overloaded virtual function 'AliVParticle::Momentum' declared here: different number of parameters (1 vs 0)
DEBUG:AliPhysics:0:   virtual void     Momentum(TLorentzVector &)  { ; }
DEBUG:AliPhysics:0:                    ^
```
I guess one could try find out whether the `AliAODPWG4Particle::Momentum` is used at all and if it's not used just write the function properly as in the base class? The `AliCaloPID` in AliPhysics, which produces the compilation warning above, uses the `AliAODPWG4Particle` in general, but does not use the `AliAODPWG4Particle::Momentum()`.

Cheers,
Hans

**Comment by gconesab** [comment]
Fixed in PR 389 by renaming the method. Need also another PR on aliphysics 2461
(note I have not recieved this notification, I have just seen it by chance)

**Comment by aaniin** [comment]
Hi @gconesab ,

Thanks for taking care of this. I close this issue then. :) 

Enjoy your weekend!
Hans
